production:
  host: localhost
  adapter: postgresql
  encoding: utf8
  pool: 5
  database: wmarket_production
  username: <%= ENV['wmarket_DATABASE_USER'] %>
  password: <%= ENV['wmarket_DATABASE_PASSWORD'] %>
